test: Add unit and integration tests
entur/terraform-google-memorystore pull request #6
Opened 2022-11-30 12:23 UTC by bvestli

2022-12-01 08:07 UTC, sindrel commented on README.md
> +This repository is versioned. Please see GitHub´s [documentation](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) describing
Versioning and release workflows are automated using Release Please, perhaps we should point to their docs?
https://github.com/googleapis/release-please#release-please

2022-12-01 08:09 UTC, sindrel commented on tests/cloud_memorystore_integration_test.go
> +	reqInstance := "projects/ent-tfmodules-dev/locations/europe-west1/instances/" + expectedName
Perhaps this string could be parameterized and/or set from environment/project variables?

2022-12-01 08:14 UTC, sindrel commented on tests/fixtures/redis/variables.tf
> +variable "init" {
Should we omit this variable, as it's not used? And just rely on testing against a live init module? Cc @Spikra

2022-12-01 08:18 UTC, sindrel requested changes
I have a few comments, but overall this looks great. I like that you've included more details on how to develop and run tests etc.

2022-12-01 13:38 UTC, bvestli commented
Thank you for good review, @sindrel. The suggested improvements is now implemented.

2022-12-02 08:46 UTC, sindrel approved these changes

2022-12-02 08:49 UTC, merged